apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-03-21T11:52:27Z
  labels:
    run: kubernetes-michael
  name: kubernetes-michael
  namespace: default
  resourceVersion: "21897"
  selfLink: /api/v1/namespaces/default/services/kubernetes-michael
  uid: ccb42518-4bcf-11e9-a458-42010a84020e
spec:
  clusterIP: 10.7.241.150
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32631
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: kubernetes-michael
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.76.36.4
